### ISSUE TITLE
error and warning links open relative paths instead of absolute

### ISSUE THREAD

**Issue by jannickj** [chaika2013/ide-haskell#33] opened 2015-01-28 14:17 UTC
a file in C:\the_path\file.hs opens C:\the_path\the_path\file.hs(which ofc doesn't exists) when clicking the link for a warning or an error.

**Comment by jannickj** [comment] 2015-01-28 16:08
If anyone else needs it to work right now then you can change the ghc-mod file
in .atom\packages\ide-haskell\lib\util-ghc-mod:
 uri to fileName under the function lint and check in the output onResult?({range.., uri <------, type, desc})
I am in a bit of a hurry and this is such a small change that I dont wanna bother with pull requests for it ;)

**Comment by lierdakil** [comment] 2015-02-08 12:51
I believe it's a duplicate of #25, is it not?

**Comment by jannickj** [comment] 2015-02-11 23:50
I believe you are correct @lierdakil however what I provide will actually fix the problem. The problem is that the mod runs ghc-mod but instead of using the fileName it knows it instead uses the filename returned from ghc-mod. In linux this problem will self correct so you won't notice it but on windows it doesn't and takes the path provided to it literal.

**Comment by lierdakil** [comment] 2015-02-12 15:16
Well, regex change suggested in #25 should work as well. The problem stems from having a colon in file path, which is interpreted as field separator by ide-haskell. However, your suggestion is valid. I need to think on it a bit. I will close this as duplicate, but I will keep your suggestion in mind.

**Closed** 2015-02-12 15:16 UTC
