### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Arengorn** [chaika2013/ide-haskell#35] opened 2015-02-02 19:04 UTC
I have Installed all dependencies running
```bash
sudo apt-get install haskell-platform
sudo apt-get install cabal-install
cabal update
cabal install stylish-haskell
cabal install ghc-mod
```
Then I attempted to run ```apm install ide-haskell``` which yielded
```bash
Installing ide-haskell to /home/arengorn/.atom/packages ✗

npm ERR! Failed resolving git HEAD (https://github.com/saschagehlich/autocomplete-plus.git) fatal: ambiguous argument 'feature/api': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (https://github.com/saschagehlich/autocomplete-plus.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (https://github.com/saschagehlich/autocomplete-plus.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (https://github.com/saschagehlich/autocomplete-plus.git) 
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/opt/atom/resources/app/apm/.apmrc" "--userconfig" "/home/arengorn/.atom/.apmrc" "install" "/tmp/d-11512-19491-1u6xu8s/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: fatal: ambiguous argument 'feature/api': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11512-19491-210w5y/npm-debug.log
```

**Comment by Daroth** [comment] 2015-02-04 23:21
I also tried
    apm install ide-haskell@0.3.0
and
    apm install ide-haskell@0.2.0

With the same kind of error.

I just installed atom a few minutes ago using the officiel deb package.

    $ apm --version                
    apm  0.134.0
    npm  2.3.0
    node 0.10.35
    python 2.7.6
git 1.9.1

**Comment by lierdakil** [comment] 2015-02-05 09:32
This is pretty much caused by autocomplete-plus transitioning to new API (following Atom itself)

Would you consider testing https://github.com/jmquigs/ide-haskell/tree/jmq-autocomplete-upgrade as per PR #34?

You can install this version by running
```bash
git clone --branch jmq-autocomplete-upgrade https://github.com/jmquigs/ide-haskell.git $HOME/.atom/packages/ide-haskell
cd $HOME/.atom/packages/ide-haskell
apm install
```
or equivalent, if you're on Linux (and probably OSX). Not sure how you would do this on Windows though.

If you encounter any bugs, please comment directly at #34.

**Comment by Daroth** [comment] 2015-02-07 09:23
The installation process went well. After that I can't figure out how to make auto-completion and code highlight work but I'm not sure it's related.

**Comment by lierdakil** [comment] 2015-02-07 09:32
For code-highlight, please install [language-haskell][1]. For autocomplete, please install [autocomplete-plus][2]. This package very much relies on those two.

Also, please, bear in mind, that this package only works for cabal projects, i.e. in Atom, you need to open directory with `*.cabal` file in it for ide-haskell to activate (preferably properly configured, but an empty file should also work)

[1]:https://atom.io/packages/language-haskell
[2]:https://atom.io/packages/autocomplete-plus

**Comment by Daroth** [comment] 2015-02-07 10:03
My issues were environments related (I use zsh so I forgot to update my bash profile). For me everything works fine now. Thanks for the quick answers.

**Comment by BeCalmedAgain** [comment] 2015-02-08 01:40
I've done all the above and I'm getting a ghc-modi could not be spawned.

ghc-modi is not installed under /usr/bin but I can find it under ~/.cabal/bin/ghc-modi

Safe to copy across?

**Comment by lierdakil** [comment] 2015-02-08 12:38
Alrighty. I deployed 0.3.1, which should fix this. Could anyone confirm, so I could close this?

@BeCalmedAgain, are you sure it's ide-haskell? It should not try to spawn ghc-modi, only ghc-mod. 

As for copying across, it's better to add ~/.cabal/bin to PATH, if you're on Linux. On OS X it's a little bit trickier though. Please see e.g. [this][1] for tips on setting application environment on OS X.

[1]:http://apple.stackexchange.com/questions/87282/in-mountain-lion-how-do-i-set-in-one-place-the-path-environment-variable-for-a/87283#87283

**Comment by BeCalmedAgain** [comment] 2015-02-08 13:15
![screenshot from 2015-02-08 23 14 29](https://cloud.githubusercontent.com/assets/9476448/6096635/4b3498d2-afe8-11e4-8013-f2b7dfa68530.png)

Screenshot from Atom showing ghc-modi

**Comment by lierdakil** [comment] 2015-02-08 13:36
@BeCalmedAgain, as you might have noticed, this error is thrown from `haskell-ghc-mod` package, and not from `ide-haskell`. These two are completely different (although I happen to be working on both, by chance).

In any case, since your screenshot looks suspiciously Linux-y, I'd advise you to try and add something like this to your `~/.bash_profile` or equivalent:

```bash
export PATH="${PATH}:${HOME}/.cabal/bin"
```

You need to re-login for this change to take effect.

Please note, that `ide-haskell` and `haskell-ghc-mod` will conflict with each other, since they provide similar functionality, so you might want to choose one over another. Alternatively, `haskell-ghc-mod` could be partially disabled in settings, so that it does not attempt to check file for errors unless prompted to. For that to happen, you need to uncheck all ticks in `haskell-ghc-mod` settings. Not sure why would you want that though.
Moving forward, I might try to merge these two, but not for a while.

**Closed** 2015-02-12 15:19 UTC
